name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: make install-all

    - name: Run app tests
      run: make test-app

    - name: Run backend tests
      run: make test-backend

  build-and-push:
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ai-rooms-backend:latest

    - name: Build and push websocket
      uses: docker/build-push-action@v4
      with:
        context: ./websocket
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ai-rooms-websocket:latest

    - name: Build and push model_workers
      uses: docker/build-push-action@v4
      with:
        context: ./model_workers
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ai-rooms-model-workers:latest

    - name: Build and push embeddings_worker
      uses: docker/build-push-action@v4
      with:
        context: ./embeddings_worker
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ai-rooms-embeddings-worker:latest
